//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from F:/development/markdown-to-todoist/src/grammar/TodoistGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITodoistGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class TodoistGrammarBaseListener : ITodoistGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.project"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProject([NotNull] TodoistGrammarParser.ProjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.project"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProject([NotNull] TodoistGrammarParser.ProjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.task"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTask([NotNull] TodoistGrammarParser.TaskContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.task"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTask([NotNull] TodoistGrammarParser.TaskContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.subtask"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubtask([NotNull] TodoistGrammarParser.SubtaskContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.subtask"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubtask([NotNull] TodoistGrammarParser.SubtaskContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.checkbox"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCheckbox([NotNull] TodoistGrammarParser.CheckboxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.checkbox"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCheckbox([NotNull] TodoistGrammarParser.CheckboxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescription([NotNull] TodoistGrammarParser.DescriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescription([NotNull] TodoistGrammarParser.DescriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.date"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDate([NotNull] TodoistGrammarParser.DateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.date"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDate([NotNull] TodoistGrammarParser.DateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.inline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInline([NotNull] TodoistGrammarParser.InlineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.inline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInline([NotNull] TodoistGrammarParser.InlineContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
