//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from F:/development/markdown-to-todoist/src/grammar/TodoistGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TodoistGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ITodoistGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProject([NotNull] TodoistGrammarParser.ProjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProject([NotNull] TodoistGrammarParser.ProjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.task"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTask([NotNull] TodoistGrammarParser.TaskContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.task"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTask([NotNull] TodoistGrammarParser.TaskContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.subtask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubtask([NotNull] TodoistGrammarParser.SubtaskContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.subtask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubtask([NotNull] TodoistGrammarParser.SubtaskContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.checkbox"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCheckbox([NotNull] TodoistGrammarParser.CheckboxContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.checkbox"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCheckbox([NotNull] TodoistGrammarParser.CheckboxContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDescription([NotNull] TodoistGrammarParser.DescriptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDescription([NotNull] TodoistGrammarParser.DescriptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDate([NotNull] TodoistGrammarParser.DateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDate([NotNull] TodoistGrammarParser.DateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TodoistGrammarParser.inline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInline([NotNull] TodoistGrammarParser.InlineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TodoistGrammarParser.inline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInline([NotNull] TodoistGrammarParser.InlineContext context);
}
