@startuml

package "input" {
  file DSL [
    DSL

    <&text>
  ]
}

package "parser" {
  [ANTLR runtime]
  [Visitor]
}

package "model" {
  [TodoistProject]
}

package "request-builder" {
  [model-handler]
  [restsharp] --> http
}

cloud {
  [todoist-rest-api]
}

DSL -> [ANTLR runtime]
[ANTLR runtime] --> [Visitor]
[Visitor] -> [TodoistProject]
[TodoistProject] --> [model-handler]
[model-handler] -> [restsharp]
http -> [todoist-rest-api]

@enduml
